const jobs = [
  {
    id: 1,
    title: "Frontend Developer Intern",
    company: "DevSpark Lagos",
    location: "Lekki, Lagos",
    latitude: 6.4421,
    longitude: 3.483,
    description: "Assist with React-based web development.",
    industry: "Tech",
    isAvailable: true,
  },
  {
    id: 2,
    title: "Backend Developer Intern",
    company: "CodeForge Nigeria",
    location: "Yaba, Lagos",
    latitude: 6.5144,
    longitude: 3.3869,
    description: "Support API development using Node.js.",
    industry: "Tech",
    isAvailable: true,
  },
  {
    id: 3,
    title: "UI/UX Design Intern",
    company: "DesignHub",
    location: "Ikeja, Lagos",
    latitude: 6.6018,
    longitude: 3.3515,
    description: "Design user-centric mobile interfaces.",
    industry: "Design",
    isAvailable: true,
  },
  {
    id: 4,
    title: "Digital Marketing Intern",
    company: "BuzzReach Media",
    location: "Surulere, Lagos",
    latitude: 6.5006,
    longitude: 3.3483,
    description: "Run Facebook/Google Ads for local clients.",
    industry: "Marketing",
    isAvailable: true,
  },
  {
    id: 5,
    title: "Software QA Tester",
    company: "BugSquash Ltd",
    location: "Victoria Island, Lagos",
    latitude: 6.4281,
    longitude: 3.4216,
    description: "Perform tests and report app bugs.",
    industry: "Tech",
    isAvailable: true,
  },
  {
    id: 6,
    title: "Content Writer Intern",
    company: "Writerly NG",
    location: "Maryland, Lagos",
    latitude: 6.5767,
    longitude: 3.3679,
    description: "Write articles and website copy.",
    industry: "Media",
    isAvailable: true,
  },
  {
    id: 7,
    title: "IT Support Intern",
    company: "SysSolve",
    location: "Ajah, Lagos",
    latitude: 6.4575,
    longitude: 3.6015,
    description: "Provide support for local network infrastructure.",
    industry: "IT",
    isAvailable: true,
  },
  {
    id: 8,
    title: "Graphic Designer",
    company: "PixelPush",
    location: "Ogba, Lagos",
    latitude: 6.6356,
    longitude: 3.3216,
    description: "Design posters and digital ads.",
    industry: "Design",
    isAvailable: true,
  },
  {
    id: 9,
    title: "Customer Support Intern",
    company: "QuickFix Tech",
    location: "Oshodi, Lagos",
    latitude: 6.5583,
    longitude: 3.3439,
    description: "Handle customer queries and escalate issues.",
    industry: "Customer Service",
    isAvailable: true,
  },
  {
    id: 10,
    title: "HR Intern",
    company: "PeopleFirst",
    location: "Ikoyi, Lagos",
    latitude: 6.4497,
    longitude: 3.4373,
    description: "Assist with recruitment and employee engagement.",
    industry: "Human Resources",
    isAvailable: true,
  },
];
